# Generated by Django 4.1.7 on 2023-04-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterurl',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
